### ISSUE TITLE
ChecklistIndexItem vs. ChecklistShow

### ISSUE THREAD

**Issue by chf2** [apopma/stronghold#1]
It looks like there's a ton of content/functionality packed into a ChecklistIndexItem and I'm worried it won't all fit in the broader project show view. You mention a Checklist Item show view but it's not clear to me from the wireframes what's in the index item view and what's in the show view. Would be good to clarify whether the index items are expected to have all of the checklist's functionality, or a subset

**Comment by apopma** [comment]
They're very nearly the same. The ProjectChecklistsIndex view will render many ChecklistIndexItem subviews, each of which contain a TaskPartial sub-subview.

A TaskPartial holds the task's description, a checkbox for setting the task done/undone, a link to (if any comments exist on the task) the TaskShow page, buttons to edit or delete the task, and a button which pops out the TaskAssignmentForm view.

The ChecklistShow view will _also_ render all associated TaskPartials, and also render the comments on that checklist. TaskShow views will render _one_ TaskPartial and all the comments on that task - they'll just render that partial in a slightly bigger font size for the task's description. If I can get to file uploads, they'll be visible on the associatable's show page.

Sorry about the confusion! It's really the TaskPartial which contains the densest amount of information.

**Comment by chf2** [comment]
OK, that makes sense. I think worst case scenario we can create a second task partial subview with less information.
