### ISSUE TITLE
Discussions Outside API?

### ISSUE THREAD

**Issue by chf2** [apopma/stronghold#2]
It looks like the plan is to create non-API routes for discussions Index and Show. Even though the plan is to have these views replace the general project show page, I think discussions should also be API routes so we don't have to break the one-page-ness of the app when we navigate to one.

**Comment by apopma** [comment]
Basecamp seems to have non-API routes for discussions index/show, so I went off my perceptions of their model. In your case, would the routes just be `api/projects/:id/discussions` and `api/projects/:project_id/discussions/:id`? I'd definitely end up swapping out the entire ProjectShow view and re-rendering a new composite DiscussionsIndex or DiscussionShow view.

**Comment by chf2** [comment]
I think it makes sense to have these within the API still. Websites that use single-page functionality will still have reloads on occasion but they are generally working with a lot more data than we will be. I'd prefer to keep everything single page unless we start seeing real performance issues. As to whether they're nested or not, I think that's personal preference and up to you. Since they're API routes the nested route will be less exposed to the user
