### ISSUE TITLE
Bootstrap Early!

### ISSUE THREAD

**Issue by chf2** [apopma/stronghold#3]
While I would leave finishing touches off until the end, I'd highly encourage you to start working with Bootstrap at a basic level from day one, in terms of organizing your subviews on each page.

**Comment by apopma** [comment]
I thought of that right as I was leaving today. It's definitely a good idea and I'm going to do it - it'd be a huge pain to put everything into Bootstrap after the fact. If nothing else, I can ensure all my subviews live on a Bootstrap grid and put in a basic navbar.
