### ISSUE TITLE
Discussions DB

### ISSUE THREAD

**Issue by chf2** [apopma/stronghold#4]
I agree discussions might not really make sense as their own model. Maybe these are just comments on a project directly?

**Comment by apopma** [comment]
So in that case, the comment's associatable_type would point to `projects`? I feel like the two are different enough to need separate models, despite their many similarities. On Basecamp, when you post a new discussion you have the option to give it a title as well as a comment-shaped body; but comments don't get a title, just a body.

**Comment by chf2** [comment]
In this case, I think it's fine to keep them separate. I apologize I missed that discussions had additional fields, I thought they were just top-level comments per se
