### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by chf2** [apopma/stronghold#5]
It's not well advertised, but Cloudinary can handle non-image files as well. We'll do a demo on Cloudinary later this week. It might be a good idea to cherry-pick one particular upload functionality you want to implement first if you get the chance, as file upload can be a bit tricky and it might make sense to break up that stretch goal given it's your first one.

**Comment by apopma** [comment]
Ideally I can be mostly agnostic about what kind of file the end user is uploading. I'd probably only need to distinguish between images and non-images: implementing embedded PDF, DOC, etc. views is almost certainly beyond my scope for this timespan. Images should come first, though. If I can't finish both, I can at least have some flavorful seed images to demo with.

On the other hand, I'd like to be able to show image thumbnails and full-size images. Cloudinary is looking pretty good - if it can handle both kinds of files, and I can still show placeholder thumbnails for non-images, I might commit to using it.
